# Generated by Django 6.0.1 on 2026-01-10 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('secondname', models.CharField(blank=True, max_length=100)),
                ('thirdname', models.CharField(blank=True, max_length=100)),
                ('fathername1', models.CharField(blank=True, max_length=100)),
                ('fathername2', models.CharField(blank=True, max_length=100)),
                ('mothername1', models.CharField(blank=True, max_length=100)),
                ('mothername2', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('native', models.CharField(blank=True, max_length=200)),
                ('present_city', models.CharField(blank=True, max_length=100)),
                ('taluk', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('cultureoflife', models.TextField(blank=True)),
                ('familyname1', models.CharField(blank=True, max_length=100)),
                ('familyname2', models.CharField(blank=True, max_length=100)),
                ('familyname3', models.CharField(blank=True, max_length=100)),
                ('familyname4', models.CharField(blank=True, max_length=100)),
                ('familyname5', models.CharField(blank=True, max_length=100)),
                ('preferred_language', models.CharField(default='en', max_length=50)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('caste', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profiles',
                'indexes': [models.Index(fields=['user', 'gender'], name='user_profil_user_id_5c9bdd_idx'), models.Index(fields=['religion', 'caste'], name='user_profil_religio_b92fc9_idx')],
            },
        ),
    ]
