# Generated by Django 6.0.1 on 2026-04-11 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('original_name', models.CharField(blank=True, help_text='Original placeholder name before connection', max_length=200, null=True)),
                ('is_placeholder', models.BooleanField(default=True)),
                ('invitation_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Invitation Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='not_sent', max_length=20)),
                ('invitation_token', models.CharField(blank=True, max_length=100)),
                ('invited_email', models.EmailField(blank=True, max_length=254)),
                ('invited_phone', models.CharField(blank=True, max_length=20)),
                ('is_alive', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='families.family')),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('placeholder_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender of the placeholder at invitation time', max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_received_invitations', to=settings.AUTH_USER_MODEL)),
                ('original_relation', models.ForeignKey(blank=True, help_text='Original relation specified when inviting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='relations.fixedrelation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genealogy_invitations', to='genealogy.person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AddressRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_code', models.CharField(choices=[('THATHA', 'THATHA'), ('PAATI', 'PAATI'), ('PERIYAPPA', 'PERIYAPPA'), ('PERIYAMMA', 'PERIYAMMA'), ('CHITHAPPA', 'CHITHAPPA'), ('CHITHI', 'CHITHI'), ('MAMA', 'MAMA'), ('ATHAN', 'ATHAN'), ('ANNI', 'ANNI'), ('KOLUNTHIYAZH', 'KOLUNTHIYAZH'), ('ATHAI', 'ATHAI'), ('ANNA', 'ANNA'), ('AKKA', 'AKKA'), ('THAMBI', 'THAMBI'), ('THANGAI', 'THANGAI'), ('KOLUNTHANAR', 'KOLUNTHANAR'), ('MARUMAGAL', 'MARUMAGAL'), ('MARUMAGAN', 'MARUMAGAN'), ('PETTHI', 'PETTHI'), ('PERAN', 'PERAN'), ('MAITHUNAR', 'MAITHUNAR'), ('MAGHAZH', 'MAGHAZH'), ('MAGAN', 'MAGAN')], max_length=30)),
                ('context', models.CharField(choices=[('ashramam', 'Ashramam')], default='ashramam', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ashramam_given', to='genealogy.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ashramam_received', to='genealogy.person')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('conflicted', 'Conflicted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('conflict_reason', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_relations', to=settings.AUTH_USER_MODEL)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='genealogy.person')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relations', to='relations.fixedrelation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='genealogy.person')),
            ],
            options={
                'db_table': 'person_relations',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['family', 'gender'], name='persons_family__be2fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['full_name', 'family'], name='persons_full_na_4a442c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['date_of_birth'], name='persons_date_of_281ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_alive', 'is_verified'], name='persons_is_aliv_8465f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addressrelation',
            unique_together={('from_person', 'to_person', 'context')},
        ),
        migrations.AddIndex(
            model_name='personrelation',
            index=models.Index(fields=['from_person', 'status'], name='person_rela_from_pe_389709_idx'),
        ),
        migrations.AddIndex(
            model_name='personrelation',
            index=models.Index(fields=['to_person', 'status'], name='person_rela_to_pers_47ef81_idx'),
        ),
        migrations.AddIndex(
            model_name='personrelation',
            index=models.Index(fields=['status', 'created_at'], name='person_rela_status_6025da_idx'),
        ),
        migrations.AddIndex(
            model_name='personrelation',
            index=models.Index(fields=['created_by', 'created_at'], name='person_rela_created_2a60b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personrelation',
            unique_together={('from_person', 'to_person', 'relation')},
        ),
    ]
