# Generated by Django 6.0.1 on 2026-01-11 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='families.family')),
                ('linked_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Persons',
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='PersonRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('conflicted', 'Conflicted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('conflict_reason', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_relations', to=settings.AUTH_USER_MODEL)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='genealogy.person')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_relations', to='relations.fixedrelation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='genealogy.person')),
            ],
            options={
                'db_table': 'person_relations',
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['family', 'gender'], name='persons_family__be2fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['full_name', 'family'], name='persons_full_na_4a442c_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['date_of_birth'], name='persons_date_of_281ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_alive', 'is_verified'], name='persons_is_aliv_8465f4_idx'),
        ),
        migrations.AddIndex(
            model_name='personrelation',
            index=models.Index(fields=['from_person', 'status'], name='person_rela_from_pe_389709_idx'),
        ),
        migrations.AddIndex(
            model_name='personrelation',
            index=models.Index(fields=['to_person', 'status'], name='person_rela_to_pers_47ef81_idx'),
        ),
        migrations.AddIndex(
            model_name='personrelation',
            index=models.Index(fields=['status', 'created_at'], name='person_rela_status_6025da_idx'),
        ),
        migrations.AddIndex(
            model_name='personrelation',
            index=models.Index(fields=['created_by', 'created_at'], name='person_rela_created_2a60b6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personrelation',
            unique_together={('from_person', 'to_person', 'relation')},
        ),
    ]
