# Generated by Django 6.0.1 on 2026-01-13 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_family_family_name'),
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='families.family'),
        ),
    ]
