# Generated by Django 5.2.4 on 2026-04-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personrelation',
            name='birth_order',
            field=models.PositiveIntegerField(blank=True, help_text='Birth order for children (1=first, 2=second, etc.)', null=True),
        ),
    ]
