# Generated by Django 5.2.4 on 2026-04-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_add_birth_order_to_person_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personrelation',
            name='birth_order',
            field=models.PositiveIntegerField(blank=True, help_text='Birth order for family relations (1=first, 2=second, etc.)', null=True),
        ),
    ]
