# Generated by Django 6.0.1 on 2026-01-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_alter_person_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='invitation_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Invitation Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='not_sent', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='invitation_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='invited_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='is_placeholder',
            field=models.BooleanField(default=True),
        ),
    ]
