# Generated by Django 6.0.1 on 2026-01-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personrelation',
            name='conflict_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
