# Generated by Django 6.0.1 on 2026-01-25 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0005_alter_personrelation_conflict_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_code', models.CharField(choices=[('THATHA', 'THATHA'), ('PAATI', 'PAATI'), ('PERIYAPPA', 'PERIYAPPA'), ('PERIYAMMA', 'PERIYAMMA'), ('CHITHAPPA', 'CHITHAPPA'), ('CHITHI', 'CHITHI'), ('MAMA', 'MAMA'), ('ATHAN', 'ATHAN'), ('ANNI', 'ANNI'), ('KOLUNTHIYAZH', 'KOLUNTHIYAZH'), ('ATHAI', 'ATHAI'), ('ANNA', 'ANNA'), ('AKKA', 'AKKA'), ('THAMBI', 'THAMBI'), ('THANGAI', 'THANGAI'), ('KOLUNTHANAR', 'KOLUNTHANAR'), ('MARUMAGAL', 'MARUMAGAL'), ('MARUMAGAN', 'MARUMAGAN'), ('PETTHI', 'PETTHI'), ('PERAN', 'PERAN'), ('MAITHUNAR', 'MAITHUNAR'), ('MAGHAZH', 'MAGHAZH'), ('MAGAN', 'MAGAN')], max_length=30)),
                ('context', models.CharField(choices=[('ashramam', 'Ashramam')], default='ashramam', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ashramam_given', to='genealogy.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ashramam_received', to='genealogy.person')),
            ],
            options={
                'unique_together': {('from_person', 'to_person', 'context')},
            },
        ),
    ]
