# Generated by Django 6.0.1 on 2026-01-28 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0006_addressrelation'),
        ('relations', '0003_alter_relationfamily_caste_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='invitation',
            name='original_relation',
            field=models.ForeignKey(blank=True, help_text='Original relation specified when inviting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='relations.fixedrelation'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='placeholder_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender of the placeholder at invitation time', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
