# Generated by Django 6.0.1 on 2026-01-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0007_alter_invitation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='original_name',
            field=models.CharField(blank=True, help_text='Original placeholder name before connection', max_length=200, null=True),
        ),
    ]
