# Generated by Django 6.0.1 on 2026-01-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(blank=True, db_index=True, default='My family', max_length=200, null=True),
        ),
    ]
