# Generated by Django 6.0.1 on 2026-04-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermission',
            name='can_manage_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffpermission',
            name='can_manage_post',
            field=models.BooleanField(default=False),
        ),
    ]
