# Generated by Django 6.0.1 on 2026-04-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_staffpermission_can_manage_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermission',
            name='can_manage_event',
            field=models.BooleanField(default=False, help_text='Can moderate events (approve/reject/flag)'),
        ),
    ]
