# Generated by Django 6.0.1 on 2026-02-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_staffpermission_can_login_with_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemConfig',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='is_two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='two_factor_method',
        ),
        migrations.RemoveField(
            model_name='staffpermission',
            name='can_login_with_email',
        ),
        migrations.RemoveField(
            model_name='staffpermission',
            name='can_login_with_mobile',
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('password_change', 'Password Change'), ('status_change', 'Status Change')], max_length=20),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
