# Generated by Django 6.0.1 on 2026-02-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_passwordresettoken_user_delete_systemconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
