# Generated by Django 6.0.1 on 2026-02-06 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_adminprofile_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationAdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('relation_create', 'Relation Created'), ('relation_update', 'Relation Updated'), ('relation_delete', 'Relation Deleted'), ('override_create', 'Override Created'), ('override_update', 'Override Updated'), ('override_delete', 'Override Deleted'), ('bulk_import', 'Bulk Import'), ('export', 'Export')], max_length=20)),
                ('description', models.TextField()),
                ('relation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('affected_level', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relation Activity Log',
                'verbose_name_plural': 'Relation Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RelationManagementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_fixed_relations', models.BooleanField(default=False)),
                ('can_manage_language_religion', models.BooleanField(default=False)),
                ('can_manage_caste_overrides', models.BooleanField(default=False)),
                ('can_manage_family_overrides', models.BooleanField(default=False)),
                ('can_view_relation_analytics', models.BooleanField(default=True)),
                ('can_export_relation_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relation Management Permission',
                'verbose_name_plural': 'Relation Management Permissions',
            },
        ),
    ]
