# Generated by Django 6.0.1 on 2026-02-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_relationadminactivitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationmanagementpermission',
            name='can_manage_profile_overrides',
            field=models.BooleanField(default=False),
        ),
    ]
