# Generated by Django 6.0.1 on 2026-02-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_relationmanagementpermission_can_manage_profile_overrides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationadminactivitylog',
            name='action',
            field=models.CharField(choices=[('relation_create', 'Relation Created'), ('relation_update', 'Relation Updated'), ('relation_delete', 'Relation Deleted'), ('override_create', 'Override Created'), ('override_update', 'Override Updated'), ('override_delete', 'Override Deleted'), ('bulk_import', 'Bulk Import'), ('export', 'Export')], max_length=50),
        ),
    ]
