# Generated by Django 6.0.1 on 2026-02-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_relationadminactivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminactivitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
