# Generated by Django 6.0.1 on 2026-01-11 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('default_english', models.CharField(max_length=100)),
                ('default_tamil', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling'), ('GRANDPARENT', 'Grandparent'), ('GRANDCHILD', 'Grandchild'), ('OTHER', 'Other')], max_length=50)),
                ('from_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], default='A', max_length=1)),
                ('to_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], default='A', max_length=1)),
                ('max_instances', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('is_reciprocal_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fixed_relations',
                'indexes': [models.Index(fields=['relation_code', 'category'], name='fixed_relat_relatio_fce03d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelationCaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=50)),
                ('religion', models.CharField(db_index=True, max_length=100)),
                ('caste', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caste_labels', to='relations.fixedrelation')),
            ],
            options={
                'db_table': 'relation_caste',
                'indexes': [models.Index(fields=['language', 'religion', 'caste'], name='relation_ca_languag_889b84_idx')],
                'unique_together': {('relation', 'language', 'religion', 'caste')},
            },
        ),
        migrations.CreateModel(
            name='RelationFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=50)),
                ('religion', models.CharField(db_index=True, max_length=100)),
                ('caste', models.CharField(db_index=True, max_length=100)),
                ('family', models.CharField(db_index=True, help_text='Family name or identifier', max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_labels', to='relations.fixedrelation')),
            ],
            options={
                'db_table': 'relation_family',
                'indexes': [models.Index(fields=['family', 'language'], name='relation_fa_family_904967_idx')],
                'unique_together': {('relation', 'language', 'religion', 'caste', 'family')},
            },
        ),
        migrations.CreateModel(
            name='RelationLanguageReligion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=50)),
                ('religion', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_religion_labels', to='relations.fixedrelation')),
            ],
            options={
                'db_table': 'relation_language_religion',
                'indexes': [models.Index(fields=['language', 'religion'], name='relation_la_languag_3e45dc_idx')],
                'unique_together': {('relation', 'language', 'religion')},
            },
        ),
    ]
