# Generated by Django 6.0.1 on 2026-04-11 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('default_english', models.CharField(max_length=100)),
                ('default_tamil', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('PARENT', 'Parent'), ('CHILD', 'Child'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling'), ('GRANDPARENT', 'Grandparent'), ('GRANDCHILD', 'Grandchild'), ('OTHER', 'Other')], max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this relation is currently active/available')),
                ('from_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], default='A', max_length=1)),
                ('to_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], default='A', max_length=1)),
                ('max_instances', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('is_reciprocal_required', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=False, help_text='Whether this is a user-defined custom relation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fixed_relations',
                'indexes': [models.Index(fields=['relation_code', 'category'], name='fixed_relat_relatio_fce03d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RelationFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=50)),
                ('lifestyle', models.CharField(db_index=True, max_length=100)),
                ('familyname8', models.CharField(db_index=True, max_length=100)),
                ('family', models.CharField(db_index=True, help_text='Family name or identifier', max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_labels', to='relations.fixedrelation')),
            ],
            options={
                'db_table': 'relation_family',
                'indexes': [models.Index(fields=['family', 'language'], name='relation_fa_family_904967_idx')],
                'unique_together': {('relation', 'language', 'lifestyle', 'familyname8', 'family')},
            },
        ),
        migrations.CreateModel(
            name='Relationfamilyname8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=50)),
                ('lifestyle', models.CharField(db_index=True, max_length=100)),
                ('familyname8', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familyname8_labels', to='relations.fixedrelation')),
            ],
            options={
                'db_table': 'relation_familyname8',
                'indexes': [models.Index(fields=['language', 'lifestyle', 'familyname8'], name='relation_fa_languag_95673e_idx')],
                'unique_together': {('relation', 'language', 'lifestyle', 'familyname8')},
            },
        ),
        migrations.CreateModel(
            name='RelationLanguagelifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=50)),
                ('lifestyle', models.CharField(db_index=True, max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_lifestyle_labels', to='relations.fixedrelation')),
            ],
            options={
                'db_table': 'relation_language_lifestyle',
                'indexes': [models.Index(fields=['language', 'lifestyle'], name='relation_la_languag_b15ccb_idx')],
                'unique_together': {('relation', 'language', 'lifestyle')},
            },
        ),
        migrations.CreateModel(
            name='RelationProfileOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil')], default='en', max_length=10)),
                ('lifestyle', models.CharField(blank=True, max_length=100, null=True)),
                ('familyname8', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=200, null=True)),
                ('native', models.CharField(blank=True, max_length=200, null=True)),
                ('present_city', models.CharField(blank=True, max_length=100, null=True)),
                ('taluk', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_overrides', to='relations.fixedrelation')),
            ],
            options={
                'db_table': 'relation_profile_overrides',
                'indexes': [models.Index(fields=['relation', 'language', 'lifestyle'], name='relation_pr_relatio_aa099f_idx'), models.Index(fields=['relation', 'language', 'lifestyle', 'familyname8'], name='relation_pr_relatio_1fa8da_idx'), models.Index(fields=['relation', 'language', 'lifestyle', 'familyname8', 'family'], name='relation_pr_relatio_68d364_idx'), models.Index(fields=['relation', 'native', 'present_city'], name='relation_pr_relatio_bd2e8b_idx'), models.Index(fields=['relation', 'district', 'state'], name='relation_pr_relatio_dd7bd1_idx'), models.Index(fields=['relation', 'nationality'], name='relation_pr_relatio_0f9bf9_idx'), models.Index(fields=['relation', 'state', 'district', 'taluk'], name='relation_pr_relatio_6d0d65_idx'), models.Index(fields=['relation', 'lifestyle', 'state'], name='relation_pr_relatio_d391cc_idx'), models.Index(fields=['relation', 'familyname8', 'district'], name='relation_pr_relatio_8a2391_idx')],
                'unique_together': {('relation', 'language', 'lifestyle', 'familyname8', 'family', 'native', 'present_city', 'taluk', 'district', 'state', 'nationality')},
            },
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('community', 'Community'), ('other', 'Other')], default='friend', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_made', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_initiated', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_connections',
                'indexes': [models.Index(fields=['user1', 'is_active'], name='user_connec_user1_i_9ffd28_idx'), models.Index(fields=['user2', 'is_active'], name='user_connec_user2_i_352902_idx'), models.Index(fields=['is_active', 'established_at'], name='user_connec_is_acti_a56207_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
