# Generated by Django 6.0.1 on 2026-04-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedrelation',
            name='composition_token',
            field=models.CharField(blank=True, help_text='Optional token used for path composition. If blank, derived from default_english.', max_length=100),
        ),
    ]
