# Generated by Django 6.0.1 on 2026-01-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationfamily',
            name='caste',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='relationfamily',
            name='family',
            field=models.CharField(blank=True, db_index=True, help_text='Family name or identifier', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relationfamily',
            name='language',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relationfamily',
            name='religion',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
