# Generated by Django 6.0.1 on 2026-01-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_alter_relationfamily_caste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationfamily',
            name='caste',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='relationfamily',
            name='family',
            field=models.CharField(db_index=True, default='my family', help_text='Family name or identifier', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relationfamily',
            name='language',
            field=models.CharField(db_index=True, default='ta', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relationfamily',
            name='religion',
            field=models.CharField(db_index=True, default='hindu', max_length=100),
            preserve_default=False,
        ),
    ]
