# Generated by Django 6.0.1 on 2026-04-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_fixedrelation_composition_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedrelation',
            name='match_token',
            field=models.CharField(blank=True, help_text='Token used to match composed paths. If blank, derived from default_english.', max_length=100),
        ),
    ]
