# Generated by Django 6.0.1 on 2026-04-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_fixedrelation_match_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedrelation',
            name='category',
            field=models.CharField(blank=True, choices=[('PARENT', 'Parent'), ('CHILD', 'Child'), ('SPOUSE', 'Spouse'), ('SIBLING', 'Sibling'), ('GRANDPARENT', 'Grandparent'), ('GRANDCHILD', 'Grandchild'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
    ]
