# Generated by Django 6.0.1 on 2026-02-15 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_alter_relationfamily_caste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationProfileOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil')], default='en', max_length=10)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=200, null=True)),
                ('native', models.CharField(blank=True, max_length=200, null=True)),
                ('present_city', models.CharField(blank=True, max_length=100, null=True)),
                ('taluk', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_overrides', to='relations.fixedrelation')),
            ],
            options={
                'db_table': 'relation_profile_overrides',
                'indexes': [models.Index(fields=['relation', 'language', 'religion'], name='relation_pr_relatio_c32d4e_idx'), models.Index(fields=['relation', 'language', 'religion', 'caste'], name='relation_pr_relatio_f278b8_idx'), models.Index(fields=['relation', 'language', 'religion', 'caste', 'family'], name='relation_pr_relatio_a4ed79_idx'), models.Index(fields=['relation', 'native', 'present_city'], name='relation_pr_relatio_bd2e8b_idx'), models.Index(fields=['relation', 'district', 'state'], name='relation_pr_relatio_dd7bd1_idx'), models.Index(fields=['relation', 'nationality'], name='relation_pr_relatio_0f9bf9_idx'), models.Index(fields=['relation', 'state', 'district', 'taluk'], name='relation_pr_relatio_6d0d65_idx'), models.Index(fields=['relation', 'religion', 'state'], name='relation_pr_relatio_d2bfea_idx'), models.Index(fields=['relation', 'caste', 'district'], name='relation_pr_relatio_6bcd48_idx')],
                'unique_together': {('relation', 'language', 'religion', 'caste', 'family', 'native', 'present_city', 'taluk', 'district', 'state', 'nationality')},
            },
        ),
    ]
