# Generated by Django 6.0.1 on 2026-02-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0004_relationprofileoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedrelation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this relation is currently active/available'),
        ),
    ]
