# Generated by Django 5.2.4 on 2026-04-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0006_add_is_custom_to_fixedrelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('community', 'Community'), ('other', 'Other')], default='friend', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('established_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests_made', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_initiated', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_connections',
                'indexes': [models.Index(fields=['user1', 'is_active'], name='user_connec_user1_i_9ffd28_idx'), models.Index(fields=['user2', 'is_active'], name='user_connec_user2_i_352902_idx'), models.Index(fields=['is_active', 'established_at'], name='user_connec_is_acti_a56207_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
