# Generated by Django 6.0.1 on 2026-03-13 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_alter_family_family_name'),
        ('genealogy', '0008_person_original_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisibilityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PUBLIC', '🌍 Public - Everyone'), ('CONNECTED', '👥 Connected People Only'), ('FAMILY', '👪 Same Family Only'), ('CASTE', '🕉️ Same Caste Only'), ('RELIGION', '⛪ Same Religion Only'), ('LOCATION', '📍 Same Location Only'), ('PRIVATE', '🔒 Only Me')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'visibility_levels',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_virtual', models.BooleanField(default=False)),
                ('virtual_link', models.URLField(blank=True)),
                ('target_religions', models.JSONField(blank=True, default=list)),
                ('target_castes', models.JSONField(blank=True, default=list)),
                ('target_families', models.JSONField(blank=True, default=list)),
                ('target_locations', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FLAGGED', 'Flagged')], default='APPROVED', max_length=20)),
                ('moderation_note', models.TextField(blank=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/%Y/%m/')),
                ('view_count', models.IntegerField(default=0)),
                ('rsvp_going', models.IntegerField(default=0)),
                ('rsvp_maybe', models.IntegerField(default=0)),
                ('rsvp_not_going', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('excluded_users', models.ManyToManyField(blank=True, related_name='excluded_from_events', to=settings.AUTH_USER_MODEL)),
                ('honorees', models.ManyToManyField(blank=True, related_name='honored_in_events', to='genealogy.person')),
                ('invited_persons', models.ManyToManyField(blank=True, related_name='event_invitations', to='genealogy.person')),
                ('invited_users', models.ManyToManyField(blank=True, related_name='event_invitations', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='event_management.event')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='event_management.eventcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='event_media/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='event_thumbnails/')),
                ('caption', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='event_management.event')),
                ('tagged_persons', models.ManyToManyField(blank=True, related_name='tagged_in_media', to='genealogy.person')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_media',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all users?')),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_event_types', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to='families.family')),
            ],
            options={
                'db_table': 'event_types',
                'ordering': ['-usage_count', 'title'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event_management.eventtype'),
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('GOING', '✅ Going'), ('MAYBE', '🤔 Maybe'), ('NOT_GOING', '❌ Not Going')], default='GOING', max_length=20)),
                ('guests_count', models.IntegerField(default=0)),
                ('guest_names', models.TextField(blank=True, help_text='Names of additional guests')),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='event_management.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_rsvps',
            },
        ),
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_events', models.BooleanField(default=True)),
                ('max_visibility', models.CharField(blank=True, choices=[('PUBLIC', '🌍 Public - Everyone'), ('CONNECTED', '👥 Connected People Only'), ('FAMILY', '👪 Same Family Only'), ('CASTE', '🕉️ Same Caste Only'), ('RELIGION', '⛪ Same Religion Only'), ('LOCATION', '📍 Same Location Only'), ('PRIVATE', '🔒 Only Me')], max_length=50, null=True)),
                ('blocked_religions', models.JSONField(blank=True, default=list)),
                ('blocked_castes', models.JSONField(blank=True, default=list)),
                ('blocked_families', models.JSONField(blank=True, default=list)),
                ('restriction_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imposed_restrictions', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_restrictions', to=settings.AUTH_USER_MODEL)),
                ('restricted_to_visibility', models.ManyToManyField(blank=True, related_name='restricted_users', to='event_management.visibilitylevel')),
            ],
            options={
                'db_table': 'user_restrictions',
            },
        ),
        migrations.CreateModel(
            name='EventConfig',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('allow_users_change_visibility', models.BooleanField(default=True)),
                ('max_allowed_visibility', models.CharField(choices=[('PUBLIC', 'Public (Least restrictive)'), ('CONNECTED', 'Connected Only'), ('FAMILY', 'Family Only'), ('CASTE', 'Caste Only'), ('RELIGION', 'Religion Only'), ('LOCATION', 'Location Only'), ('PRIVATE', 'Private (Most restrictive)')], default='PUBLIC', max_length=50)),
                ('enable_religion_filter', models.BooleanField(default=False)),
                ('enable_caste_filter', models.BooleanField(default=False)),
                ('enable_family_filter', models.BooleanField(default=False)),
                ('enable_location_filter', models.BooleanField(default=False)),
                ('enable_connection_filter', models.BooleanField(default=True)),
                ('blocked_religions', models.JSONField(blank=True, default=list)),
                ('blocked_castes', models.JSONField(blank=True, default=list)),
                ('blocked_families', models.JSONField(blank=True, default=list)),
                ('blocked_locations', models.JSONField(blank=True, default=list)),
                ('require_moderation', models.BooleanField(default=False)),
                ('auto_approve_trusted_users', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('default_visibility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='event_management.visibilitylevel')),
            ],
            options={
                'db_table': 'event_config',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='event_management.visibilitylevel'),
        ),
        migrations.CreateModel(
            name='EventFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('INAPPROPRIATE', 'Inappropriate content'), ('SPAM', 'Spam'), ('WRONG_VISIBILITY', 'Wrong visibility settings'), ('HARASSMENT', 'Harassment'), ('FAKE', 'Fake event'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='event_management.event')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event_flags',
                'indexes': [models.Index(fields=['status', 'created_at'], name='event_flags_status_f95502_idx')],
                'unique_together': {('event', 'reported_by')},
            },
        ),
        migrations.AddIndex(
            model_name='eventtype',
            index=models.Index(fields=['title'], name='event_types_title_fad4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtype',
            index=models.Index(fields=['created_by'], name='event_types_created_cee688_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtype',
            index=models.Index(fields=['family'], name='event_types_family__9b1ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='rsvp',
            index=models.Index(fields=['event', 'response'], name='event_rsvps_event_i_e7237e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together={('event', 'user')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'status'], name='events_start_d_569f54_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', 'status'], name='events_created_d21bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['visibility', 'start_date'], name='events_visibil_368446_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city', 'state'], name='events_city_0a7c0f_idx'),
        ),
    ]
