# Generated by Django 6.0.1 on 2026-03-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='event_covers/%Y/%m/'),
        ),
    ]
