# Generated by Django 5.2.4 on 2026-04-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='post_thumbnails/%Y/%m/%d/'),
        ),
    ]
