# Generated by Django 5.2.4 on 2026-04-20 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50, unique=True)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_template', models.TextField()),
                ('sms_template', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_websocket', models.BooleanField(default=True)),
                ('enable_email', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('event_notifications', models.BooleanField(default=True)),
                ('post_notifications', models.BooleanField(default=True)),
                ('family_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('daily_digest', models.BooleanField(default=False)),
                ('weekly_digest', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_cancelled', 'Event Cancelled'), ('event_reminder', 'Event Reminder'), ('event_starting_soon', 'Event Starting Soon'), ('event_ended', 'Event Ended'), ('rsvp_received', 'RSVP Received'), ('rsvp_updated', 'RSVP Updated'), ('event_comment', 'Event Comment'), ('event_media_added', 'Event Media Added'), ('post_created', 'Post Created'), ('post_updated', 'Post Updated'), ('post_liked', 'Post Liked'), ('post_commented', 'Post Commented'), ('post_shared', 'Post Shared'), ('post_mentioned', 'Mentioned in Post'), ('post_reported', 'Post Reported'), ('relation_added', 'New Family Member Added'), ('relation_confirmed', 'Relationship Confirmed'), ('relation_updated', 'Relationship Updated'), ('birth_order_updated', 'Birth Order Updated'), ('family_anniversary', 'Family Anniversary'), ('death_anniversary', 'Death Anniversary'), ('birthday_reminder', 'Birthday Reminder'), ('profile_update', 'Profile Update Required'), ('security_alert', 'Security Alert'), ('login_alert', 'New Login Detected'), ('data_export_ready', 'Data Export Ready'), ('backup_completed', 'Backup Completed'), ('system_maintenance', 'System Maintenance')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_via_websocket', models.BooleanField(default=False)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_5cf777_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_4b40ec_idx'), models.Index(fields=['priority', 'created_at'], name='notificatio_priorit_22e6c2_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_66996e_idx')],
            },
        ),
    ]
